###
POST https://ecom-5hvo.onrender.com/insert/
### 
POST https://ecom-5hvo.onrender.com/insert/brand
###
POST https://ecom-5hvo.onrender.com/insert/category
###
POST https://e-commerce-project-q3i1.onrender.com/user/register